name: Release worflow

on:
  push:
    branches:

jobs:
  # release:
  #   name: Release packages
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #       with:
  #         fetch-depth: 0
  #         persist-credentials: false # GITHUB_TOKEN must not be set for the semantic release
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 14.17.6
  #     - name: Bootstrap
  #       run: yarn bootstrap --ci
  #     - name: Echo
  #       run: echo ${{ secrets.NPM_TOKEN }}
  #     - name: Configure npm
  #       run: |
  #         echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}' > .npmrc
  #         cat .npmrc
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  #     - name: 'Run multi-semantic-release'
  #       run: '$(yarn bin)/multi-semantic-release --deps.bump=override'
  #     - name: 'Git commit'
  #       run: '$(yarn bin)/semantic-release -p @semantic-release/git'
  #   env:
  #       GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  #       GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
  #       GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
  #       GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
  #       GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
  #       NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  extract_branch_name
    name: Extract branch name
    shell: bash
    run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    id: extract_branch

  doc:
    name: Publish doc
    runs-on: ubuntu-latest
    environment:
      name: github-pages-${{ steps.extract_branch.outputs.branch }}
    # needs: [release]
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Archive documentation artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: api-reference
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
